udpxy: add hotplug script and improve config
Add hotplug script for udpxy.
Update init script to use interface names in
uci config instead of device names.
Allow udpxy to be started or stopped by instance.

diff --git a/net/udpxy/files/udpxy.init b/net/udpxy/files/udpxy.init
--- a/net/udpxy/files/udpxy.init
+++ b/net/udpxy/files/udpxy.init
@@ -4,6 +4,9 @@
 START=50
 USE_PROCD=1
 
+EXTRA_COMMANDS="istop"
+EXTRA_HELP="istop <name>  Stop instance <name>"
+
 append_arg() {
 	local cfg="$1"
 	local var="$2"
@@ -28,21 +31,54 @@ append_bool() {
 
 start_instance() {
 	local cfg="$1"
-	local aux
+	local disabled respawn bind_if listen_if bind_dev listen_dev
+	config_get_bool disabled "$cfg" 'disabled' '0'
+	[ "$disabled" = 1 ] && return 1
 
-	config_get_bool aux "$cfg" 'disabled' '0'
-	[ "$aux" = 1 ] && return 1
+	config_get bind_if "$cfg" bind
+	config_get listen_if "$cfg" source
 
-	procd_open_instance
+	[ -n "$bind_if" ] && {
+		network_is_up $bind_if || {
+			logger -t udpxy "Skipping udpxy instance $cfg. Interface $bind_if to bind but not up."
+			return 1
+		} 
+	}
+
+	[ -n "$listen_if" ] && {
+		network_is_up $listen_if || {
+			logger -t udpxy "Skipping udpxy instance $cfg. Interface $listen_if to listen but not up."
+			return 1
+		} 
+	}
+
+	network_get_device bind_dev "$bind_if";
+	network_get_device listen_dev "$listen_if";
+
+	[ -n "$bind_if" -a -z "$bind_dev" ] && {
+		logger -t udpxy "Skipping udpxy instance $cfg. Interface $bind_if to bind but device not found."
+		return 1
+	}
+	[ -n "$listen_if" -a -z "$listen_dev" ] && {
+		logger -t udpxy "Skipping udpxy instance $cfg. Interface $bind_if to listen but device not found."
+		return 1
+	}
+	
+	procd_open_instance "$cfg"
 
 	procd_set_param command /usr/bin/udpxy
 	procd_append_param command "-T"
 
+	[ -n "$bind_if" ] && {
+		procd_append_param command "-a" "$bind_dev"
+	}
+	[ -n "$listen_if" ] && {
+		procd_append_param command "-m" "$listen_dev"
+	}
+	
 	append_bool "$cfg" verbose "-V"
 	append_bool "$cfg" status "-S"
-	append_arg "$cfg" bind "-a"
 	append_arg "$cfg" port "-p"
-	append_arg "$cfg" source "-m"
 	append_arg "$cfg" max_clients "-c"
 	append_arg "$cfg" log_file "-l"
 	append_arg "$cfg" buffer_size "-B"
@@ -51,8 +87,8 @@ start_instance() {
 	append_arg "$cfg" nice_increment "-n"
 	append_arg "$cfg" mcsub_renew "-M"
 
-	config_get_bool aux "$cfg" 'respawn' '0'
-	[ "$aux" = 1 ] && procd_set_param respawn
+	config_get_bool respawn "$cfg" 'respawn' '0'
+	[ "$respawn" = 1 ] && procd_set_param respawn
 
 	procd_close_instance
 }
@@ -63,5 +99,27 @@ service_triggers() {
 
 start_service() {
 	config_load udpxy
-	config_foreach start_instance udpxy
+	. /lib/functions/network.sh
+	if [ $# -gt 0 ]
+	then
+		for name in $@
+		do
+			start_instance $name
+		done
+	else 
+		config_foreach start_instance udpxy
+	fi
+}
+
+istop() {
+	. /lib/functions/procd.sh
+	if [ $# -gt 0 ]
+	then
+		for name in $@
+		do
+			procd_kill udpxy $name
+		done
+	else 
+		service_stop /usr/bin/udpxy
+	fi
 }
